name: Generate MMAR Modules Meta JSON
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      
      - name: Setup Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install gitpython
      
      - name: Generate JSON
        run: |
          export REPO_NAME="Magisk-Modules-Alt-Repo" 
          export REPO_TITLE="Magisk Modules Alt Repo"
          export REPO_SUBMIT_MODULE="https://github.com/Magisk-Modules-Alt-Repo/submission"
          export REPO_SCOPE="mmar"
          export GIT_TOKEN="${{ secrets.AUTH_KEY }}"
          python generate-modules.py "${{ secrets.TOKEN }}"

      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.TOKEN }}
          files: zips/*.zip

  build:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
